"""using schema public

Revision ID: 3ba36ca42f0c
Revises: 2fd59116065d
Create Date: 2024-06-20 18:19:50.044691

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba36ca42f0c'
down_revision: Union[str, None] = '2fd59116065d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pomodoro_id', table_name='pomodoro')
    op.create_index(op.f('ix_public_pomodoro_id'), 'pomodoro', ['id'], unique=False, schema='public')
    op.drop_constraint('pomodoro_task_id_fkey', 'pomodoro', type_='foreignkey')
    op.create_foreign_key(None, 'pomodoro', 'task', ['task_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_index('ix_project_id', table_name='project')
    op.create_index(op.f('ix_public_project_id'), 'project', ['id'], unique=False, schema='public')
    op.drop_index('ix_task_id', table_name='task')
    op.create_index(op.f('ix_public_task_id'), 'task', ['id'], unique=False, schema='public')
    op.drop_constraint('task_project_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', schema='public', type_='foreignkey')
    op.create_foreign_key('task_project_id_fkey', 'task', 'project', ['project_id'], ['id'])
    op.drop_index(op.f('ix_public_task_id'), table_name='task', schema='public')
    op.create_index('ix_task_id', 'task', ['id'], unique=False)
    op.drop_index(op.f('ix_public_project_id'), table_name='project', schema='public')
    op.create_index('ix_project_id', 'project', ['id'], unique=False)
    op.drop_constraint(None, 'pomodoro', schema='public', type_='foreignkey')
    op.create_foreign_key('pomodoro_task_id_fkey', 'pomodoro', 'project', ['task_id'], ['id'])
    op.drop_index(op.f('ix_public_pomodoro_id'), table_name='pomodoro', schema='public')
    op.create_index('ix_pomodoro_id', 'pomodoro', ['id'], unique=False)
    # ### end Alembic commands ###
