"""add tablename

Revision ID: 4c69bf936571
Revises: 3ba36ca42f0c
Create Date: 2024-06-20 18:45:24.905392

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c69bf936571'
down_revision: Union[str, None] = '3ba36ca42f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_public_pomodoro_id', table_name='pomodoro')
    op.create_index(op.f('ix_pomodoro_id'), 'pomodoro', ['id'], unique=False)
    op.drop_index('ix_public_project_id', table_name='project')
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.drop_index('ix_public_task_id', table_name='task')
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.create_index('ix_public_task_id', 'task', ['id'], unique=False)
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.create_index('ix_public_project_id', 'project', ['id'], unique=False)
    op.drop_index(op.f('ix_pomodoro_id'), table_name='pomodoro')
    op.create_index('ix_public_pomodoro_id', 'pomodoro', ['id'], unique=False)
    # ### end Alembic commands ###
